rules:
  anchors:
    forbid-unused-anchors: true
  document-start: disable
  empty-values: enable
  indentation:
    spaces: 2
    check-multi-line-strings: true
  line-length: disable
  quoted-strings:
    required: only-when-needed
    extra-allowed: ["{|}"]
  key-duplicates: {}
  octal-values:
    forbid-implicit-octal: true
