# Generic, formatter-friendly config.
select = ["B","B9","C","D","DAR","E","F,"I","N","RST","S","W"]

# Never enforce `E501` (line length violations). This should be handled by formatters.
ignore = ["E501"]
