name: Trunk Annotations for PRs

on:
  workflow_run:
    workflows: [Tests for PRs]
    types: [completed]

jobs:
  trunk_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Trunk Check
        uses: trunk-io/trunk-action@v1
        with:
          post-annotations: true
