name: Release

on:
  workflow_dispatch:
    inputs:
      ReleaseHeader:
        description: The header to be added to the release.
        required: false

jobs:
  Release:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.10.2
        with:
          versionSpec: '5.x'
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.10.2
      - name: Update Changelog
        id: changelog
        uses: natescherer/changelog-management-action@v1
        with:
          mode: release
          releaseVersion: ${{ steps.gitversion.outputs.SemVer }}
      - name: Push SemVer Tag
        uses: rickstaa/action-create-tag@v1
        with:
          tag: v${{ steps.gitversion.outputs.SemVer }}
      - name: Push 'latest' Tag
        uses: rickstaa/action-create-tag@v1
        with:
          tag: latest
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          base: main
          commit-message: Release v${{ steps.gitversion.outputs.SemVer }}
          branch: release/v${{ steps.gitversion.outputs.SemVer }}
          title: Release v${{ steps.gitversion.outputs.SemVer }}
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: v${{ steps.gitversion.outputs.SemVer }}
          files: 'out'
          tag_name: v${{ steps.gitversion.outputs.SemVer }}
          body: |
            # Release v${{ steps.gitversion.outputs.SemVer }}
            ${{ github.event.inputs.ReleaseHeader}}

            ## Changes
            ${{ steps.changelog.outputs.releasenotes }}