name: Start Release Process

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  Release:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v1.1.1
        with:
          versionSpec: '5.x'
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v1.1.1
      - name: Update Changelog
        id: changelog
        uses: natescherer/changelog-management-action@v1
        with:
          mode: release
          releaseVersion: ${{ steps.gitversion.outputs.SemVer }}
      - name: Create Template Zip
        uses: thedoctor0/zip-release@0.7.6
        with:
          filename: template/template_copy.zip
          path: template
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          base: main
          commit-message: "chore: release v${{ steps.gitversion.outputs.SemVer }}"
          branch: release/v${{ steps.gitversion.outputs.SemVer }}
          title: "chore: release v${{ steps.gitversion.outputs.SemVer }}"
          body: Metadata update for release v${{ steps.gitversion.outputs.SemVer }}
      - name: Create Tags in PR
        run: |
          git config user.name ${{ github.actor }}
          git config user.email ${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com
          git checkout release/${{ steps.gitversion.outputs.SemVer }}
          git tag -a v${{ steps.gitversion.outputs.SemVer }} -m v${{ steps.gitversion.outputs.SemVer }}
          git push origin --tags